-- 3-1
CREATE TABLE EX3_6(
    employee_id  NUMBER(6) PRIMARY KEY,
    EMP_NAME VARCHAR2(20),
    salary NUMBER(8,2) NOT NULL,
    MANAGER_ID NUMBER
);

INSERT INTO EX3_6 (EMPLOYEE_ID, EMP_NAME, SALARY, MANAGER_ID)
SELECT EMPLOYEE_ID, EMP_NAME, SALARY, MANAGER_ID FROM employees
WHERE MANAGER_ID = 124 AND SALARY BETWEEN 2000 AND 3000;

SELECT * FROM EX3_6;

-- 3-2
CREATE TABLE EX3_3(
    EMPLOYEE_ID NUMBER,
    BONUS_AMT NUMBER DEFAULT 0
);

INSERT INTO EX3_3 (EMPLOYEE_ID)
SELECT E.EMPLOYEE_ID
FROM EMPLOYEES E, SALES S
WHERE E.EMPLOYEE_ID = S.EMPLOYEE_ID
AND S.SALES_MONTH BETWEEN '200010' AND '200012'
GROUP BY E.EMPLOYEE_ID;
COMMIT;

SELECT * FROM EX3_3;

SELECT EMPLOYEE_ID, MANAGER_ID, SALARY, SALARY * 0.5
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EX3_3)
AND MANAGER_ID = 145;

MERGE INTO EX3_3 D
    USING (SELECT EMPLOYEE_ID, SALARY, MANAGER_ID
                        FROM employees
                        WHERE MANAGER_ID =145) B
    ON (D.EMPLOYEE_ID = B.EMPLOYEE_ID)
WHEN MATCHED THEN
    UPDATE SET D.BONUS_AMT = D.BONUS_AMT * 0.01
WHEN NOT MATCHED THEN
    INSERT (D.EMPLOYEE_ID, D.BONUS_AMT) VALUES (B.EMPLOYEE_ID, B.SALARY * 0.5);

SELECT * FROM EX3_3;

DROP TABLE EX3_3;

-- 3-3
SELECT EMPLOYEE_ID, EMP_NAME FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

-- 3-4
SELECT EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 2000 AND 2500
ORDER BY employee_id;

SELECT EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE SALARY >= 2000 AND SALARY<= 2500
ORDER BY employee_id;

-- 3-5
SELECT EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE SALARY IN (2000,3000,4000)
ORDER BY EMPLOYEE_ID;

SELECT EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE SALARY = ANY(2000,3000,4000)
ORDER BY EMPLOYEE_ID;

SELECT EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE SALARY NOT IN (2000,3000,4000)
ORDER BY EMPLOYEE_ID;

SELECT EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE SALARY != ALL(2000,3000,4000)
ORDER BY EMPLOYEE_ID;